
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class cau5 extends javax.swing.JFrame {

    
    public cau5() {
        initComponents();
        modelList.addElement(4);
        modelList.addElement(5);
        modelList.addElement(6);
        modelList.addElement(9);
        modelList.addElement(11);
        modelList.addElement(17);
        modelList.addElement(18);
        jList.setModel(modelList); 
    }
    private void getListItems(String type) { 
        
        ArrayList<Integer> arrList = new ArrayList<Integer>(); 
 
        if (type.equals("EVEN")) { 
            for (int i = 0; i < modelList.size(); i++) 
        { 
                int item = Integer.parseInt(modelList.get(i).toString()); 
                if (item % 2 == 0) { 
                    arrList.add(i); 
                } 
            } 
            selectedItemList = new int[arrList.size()]; 
 
            for (int i = 0; i < arrList.size(); i++) { 
                selectedItemList[i] = arrList.get(i); 
            } 
        } else if (type.equals("PRIME")) { 
            for (int i = 0; i < modelList.size(); i++) 
{ 
                int item = Integer.parseInt(modelList.get(i).toString()); 
                if (isPrime(item)) { 
                    arrList.add(i); 
                } 
            } 
            selectedItemList = new int[arrList.size()]; 
             
            for (int i = 0; i < arrList.size(); i++) { 
                selectedItemList[i] = arrList.get(i); 
            } 
        } else if (type.equals("ODD")) { 
            for (int i = 0; i < modelList.size(); i++) 
        {    
                int item = Integer.parseInt(modelList.get(i).toString()); 
                if (item % 2 == 1) { 
                    arrList.add(i); 
                } 
            } 
            selectedItemList = new int[arrList.size()]; 
 
            for (int i = 0; i < arrList.size(); i++) { 
                selectedItemList[i] = arrList.get(i); 
            } 
        } 
    } 
        private boolean isPrime(int number) { 
        if (number <= 1) { 
            return false; 
        } 
 
        for (int i = 2; i < number; i++) { 
            if (number % i == 0) { 
                return false; 
            } 
        } 
        return true; 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnTodenChan = new javax.swing.JButton();
        btnTodenLe = new javax.swing.JButton();
        btnTodenNT = new javax.swing.JButton();
        btnTodenExit = new javax.swing.JButton();
        btnTodenDelete = new javax.swing.JButton();
        btnSum = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        btnInput = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        cbNhapAm = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204)), "Chọn tác vụ", 0, 0, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btnTodenChan.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnTodenChan.setText("Tô đen số chẵn");
        btnTodenChan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodenChanActionPerformed(evt);
            }
        });

        btnTodenLe.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnTodenLe.setText("Tô đen số lẻ");
        btnTodenLe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodenLeActionPerformed(evt);
            }
        });

        btnTodenNT.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnTodenNT.setText("Tô đen số Nguyên tố");
        btnTodenNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodenNTActionPerformed(evt);
            }
        });

        btnTodenExit.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnTodenExit.setText("Bỏ tô đen");
        btnTodenExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodenExitActionPerformed(evt);
            }
        });

        btnTodenDelete.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnTodenDelete.setText("Xóa các giá trị tô đen");
        btnTodenDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodenDeleteActionPerformed(evt);
            }
        });

        btnSum.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnSum.setText("Tổng giá trị trong List");
        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTodenExit)
                            .addComponent(btnTodenDelete)
                            .addComponent(btnSum)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTodenLe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTodenNT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTodenChan, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTodenChan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTodenLe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTodenNT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTodenExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTodenDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSum)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204)), "Nhập thông tin", 0, 0, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setViewportView(jList);

        btnInput.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnInput.setText("Nhập");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        cbNhapAm.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        cbNhapAm.setText("Nhập số âm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbNhapAm)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInput)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNhapAm))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));

        btnClose.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnClose.setText("Đóng chương trình");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("BÀI 5 : THAO TÁC TRÊN JLIST");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultListModel modelList = new DefaultListModel();
    int[] selectedItemList = null;
    
    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
                int inputNumber = 0; 
 
        try { 
            inputNumber = Integer.parseInt(txtInput.getText().toString()); 
 
            if (inputNumber < 0 && !cbNhapAm.isSelected()) { 
                JOptionPane.showMessageDialog(this, "Khong duoc nhap so am", "Canh Bao",JOptionPane.ERROR_MESSAGE); 
                            } else { 
                modelList.addElement(inputNumber); 
                txtInput.setText(""); 
            } 
 
        } catch (Exception ex) { 
            JOptionPane.showMessageDialog(this, "Vui long nhap so", "Canh Bao", JOptionPane.ERROR_MESSAGE); 
            txtInput.setText(""); 
        }    
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnTodenChanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodenChanActionPerformed
            getListItems("EVEN"); 
            jList.setSelectedIndices(selectedItemList); 
    }//GEN-LAST:event_btnTodenChanActionPerformed

    private void btnTodenLeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodenLeActionPerformed
        // TODO add your handling code here:
            getListItems("ODD"); 
            jList.setSelectedIndices(selectedItemList); 
    }//GEN-LAST:event_btnTodenLeActionPerformed

    private void btnTodenNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodenNTActionPerformed
        // TODO add your handling code here:
            getListItems("PRIME"); 
            jList.setSelectedIndices(selectedItemList);
    }//GEN-LAST:event_btnTodenNTActionPerformed

    private void btnTodenExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodenExitActionPerformed
        // TODO add your handling code here:
        if (jList.getSelectedIndex() == -1) { 
            JOptionPane.showMessageDialog(this, "Ban chua chon so nao", "Canh Bao", JOptionPane.ERROR_MESSAGE); 
            } else { 
 
            jList.removeSelectionInterval(selectedItemList[0], selectedItemList[selectedItemList.length - 1]); 
        } 
    }//GEN-LAST:event_btnTodenExitActionPerformed

    private void btnTodenDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodenDeleteActionPerformed
        // TODO add your handling code here:
                if (jList.getSelectedIndex() == -1) { 
            JOptionPane.showMessageDialog(this, "Ban chua chon so nao", "Canh Bao", JOptionPane.ERROR_MESSAGE); 
        } else { 
            for (int i = 0; i < selectedItemList.length; i++) { 
                modelList.removeElement(jList.getSelectedValue());
            }
        }
    }//GEN-LAST:event_btnTodenDeleteActionPerformed

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        // TODO add your handling code here:
                if (modelList.size() == 0) { 
            JOptionPane.showMessageDialog(this, "Danh sach bi rong", "Canh Bao", JOptionPane.WARNING_MESSAGE); 
        } else { 
            int sum = 0; 
            for (int i = 0; i < modelList.size(); i++) 
{ 
                int num = 
                        
                        Integer.parseInt(modelList.get(i).toString()); 
                sum += num; 
            } 
 
            JOptionPane.showMessageDialog(this, "Tong cac con so trong JList: " + sum); 
        } 
    }//GEN-LAST:event_btnSumActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cau5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cau5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cau5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cau5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cau5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnSum;
    private javax.swing.JButton btnTodenChan;
    private javax.swing.JButton btnTodenDelete;
    private javax.swing.JButton btnTodenExit;
    private javax.swing.JButton btnTodenLe;
    private javax.swing.JButton btnTodenNT;
    private javax.swing.JCheckBox cbNhapAm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
